### ISSUE TITLE
Consider deprecating in favor of husky?

### ISSUE THREAD

**Issue by kentcdodds** [gtramontina/ghooks#166]
Hey friends! So I recently found another similar module called [`husky`](https://github.com/typicode/husky). I've tried it on a few of my projects and really like it. Here are a few reasons I think it'd be great to deprecate ghooks and put our efforts behind husky:
1. It's good to merge projects/choose a "winner" when that can reasonably be done and focus efforts
2. They support git GUIs #40
3. Config is slightly simpler

Thoughts? 💭

**Comment by kentcdodds** [comment]
I'm personally going to stop working on ghooks in favor of husky. Removing myself from the list of collaborators and unwatching. Let's merge efforts.

**Comment by okonet** [comment]
Not sure it's possible to do something like this with husky though:

https://gist.github.com/okonet/9706ec3b7f29e05109f3744fbc1fc91e

**Comment by kentcdodds** [comment]
Thanks for bringing this up. I had to do a little research, but I found that husky will store the parameters in an environment variable called `GIT_PARAMS` which you can access in your script :+1:

Honestly, it's not quite as nice IMO, but it's not a terrible solution, and there aren't a lot of use cases you need those args so I'm good with it.

**Comment by gtramontina** [comment]
Sorry, I've never got back to this one… _<insert lame excuse here 😊>_

Yeah, I'm definitely in favour of sticking with a "winner". Actually, I'm looking for someone to maintain this project. By maintain I mean to support those who have to stay on `ghooks` (for whatever reason) until they move out. I'm going to spare some time to tidy this repo up and update the readme to mention that…

As far as passing the parameters to the script, perhaps this is the opportunity to collaborate and  makeapullrequest.com to husky. 😄

**Comment by kentcdodds** [comment]
>  I'm going to spare some time to tidy this repo up and update the readme to mention that…

Sounds great!

As for looking for another maintainer, I don't know what more help people need. Luckily a migration from ghooks to husky is pretty simple and straightforward (with the exception of the parameters thing, which most people aren't using).

**Comment by thecotne** [comment]
@kentcdodds @gtramontina please add deprecation warning in readme so newcomers know that  husky is more supported and maintained solution

**Comment by kentcdodds** [comment]
Good idea @thecotne. Fancy making a PR?

**Comment by AdriVanHoudt** [comment]
There should be a notice on how to move to husky, as in how to uninstall the ghooks git hooks before installing husky

**Comment by kentcdodds** [comment]
True, would you like to make a pull request?

**Comment by AdriVanHoudt** [comment]
I don't know what the right solution is. Deleting all your git hooks seems dangerous (unless you know what you're doing), asking the rest of my team to do that is also tedious.

**Comment by kentcdodds** [comment]
Anyone using ghooks or husky will be managing all of their git hooks via the tool and will most likely not have any custom git hooks. So we could probably simply say:

> To migrate from ghooks to husky, delete all of your git hooks first by deleting the `.git/hooks` directory (if you have any custom hooks, you should preserve those by deleting all other hooks individually). Then uninstall `ghooks` and install `husky`.

We could take it a step further and add a `postuninstall` hook to `ghooks` that deletes all of the hooks that are generated by `ghooks`. That'd make the process and instructions easier. But I'm afraid I can't commit any more time to this package.

**Comment by kentcdodds** [comment]
Also, I'm going to go ahead and close this because the deprecation warning is good enough for me.

**Comment by AdriVanHoudt** [comment]
@kentcdodds would you be ok with a PR to add that text to the readme or is that overkill on the deprecation notice?

**Comment by kentcdodds** [comment]
I'd be fine with that, but I'm no longer able to merge pull requests.

**Comment by AdriVanHoudt** [comment]
@gtramontina do you have an opinion on this?

**Comment by gtramontina** [comment]
Hey hey… sorry about the silence. Yeah, absolutely! I'm also noticing a few references to this issue. I'll get @kentcdodds' message, which looks just fine, and reference one of @st3v3nhun's commits as an example. Thank you all!

**Comment by jamietre** [comment]
Just wanted to make an observation to those considering switching (which is what led me here) - husky does not seem to play well with windows since it works by generating shell scripts; indeed there's an [open issue](https://github.com/typicode/husky/issues/76). 

Anything that depends on a shell environment is going to be tricky to make work reliably on windows. There's no guarantee a windows user even has git bash installed at all.

**Comment by kentcdodds** [comment]
Oh, now _that's_ a concern... I was under the impression husky worked cross-platform... 🤔 perhaps we should help make that happen.

**Comment by jamietre** [comment]
I looked at the source briefly, and while it's pretty straightforward, it would kinda be a rewrite... the whole thing works by using shell scripts. :/  in that sense ghooks might already be in a better place?? 

I have no dog in the game either way (I use ghooks now, but it's so simple to implement that changing to something else is not a big deal). And I also don't know what the problems with ghooks are that led to the deprecation.. or if just generally this was conceding to their greater stars and momentum :)

But from the xplat perspective, ghooks seems like a better implementation, bugs notwithstanding. Not quite sure I understand the GUI support issue you mentioned at the top here though, which seems to be one of the points towards migrating to husky. We have people using ghooks with webstorm & VSCode and it works, But seems related (e.g. scripting vs. node).

**Comment by gtramontina** [comment]
That was one of the reasons why I initially started `ghooks` with node scripts (cross-platform)…

I just got back from a short off-the-grid time off and am now swamped with work again… I'd be happy to add/transfer ownership to anyone interested in maintaining this project. I'd suggest getting in touch with @typicode. Joining forces with husky would, perhaps, be better for everyone…

**Comment by typicode** [comment]
@gtramontina @kentcdodds First :heart: for linking to husky.

@jamietre Actually, most of the time, when you install Git on Windows it comes with shell support. That's at least the case with [Git installer](https://git-scm.com/), [Git Desktop](https://desktop.github.com/) and probably most IDEs that comes with Git.

I'm not aware of all the tools and may be wrong, but I would say the common use cases are covered on Windows.

That said, I would be interested in knowing if there are popular Windows tools that comes without Git bash. This way husky could maybe better handle them (there's this [issue](https://github.com/typicode/husky/issues/76)).

Another advantage of the shell, is that if you're relying on `nvm` it's easier to work with it and GUI apps on OS X and Linux.

But as always, pick what you're more confortable with :)

**Comment by jamietre** [comment]
@typicode Thanks for jumping in! I think everyone wants the same thing which is a single good solution that works for all users. So if it was just me I was worried it would be really simple! But even within my organization we have to support a lot of different configs - so I can't just pick something that works for me.

For background - I'm one of the few, the proud (?)... the Windows node developers. I wouldn't say it's by choice, but there it is. I have spent a lot of time over the last few years dealing with Windows incompatibilities, and also in trying to create a good command line environment for Windows, so I have a lot of experience with the nuances of the environment, and particularly with compatibility issues, since I use software frequently that has rarely been used by other Windows users. My company is primarily a Windows shop, but we host node applications on Linux, have a handful of devs using Linux, and some using the Windows Bash, a number which is slowly increasing.

So - the primary sticking point comes here, when you install Git for Windows:

![image](https://cloud.githubusercontent.com/assets/573056/22022469/361b88ee-dc90-11e6-82ca-21fe938073fa.png)

While it does actually install the git bash with git, (and it would be hard to not have one), unless you select that red option with the big warning, the git tools are only available from a git bash. You'd be surprised how often this is not the case. While I personally can't live without the linux tools, half the time when I pop onto someone's computer here, and they're in a CMD shell, and type `ls` I get "command not found."

So anyway if you are only working from a command line, and you only ever work within the git bash, then, maybe no problem. But that doesn't cover lots of other possibilities in windows.

* When you launch git from a GUI app, it starts a new shell using the default Windows shell, which will almost always be CMD - and have no bash support
* The git bash doesn't support linux binaries like zsh, so if you're interested in something that isn't awful and supports even basic command line editing, you probably use don't use the git bash, but use TCC, or maybe even PowerShell.

Even if you have git bash support in a default shell, compatibility problems come up. Some things just aren't supported:

* using `&` to spawn a new process
* filenames - Windows file paths have spaces a lot, and use a backslash to separate path segments. This requires a lot of careful handling to work correctly when generating scripts.
* while most common commands are ported in the git bash, many bash script constructs just aren't available (like if/fi}. It's not actually a bash shell. It just has some of the common utilities compiled in windows.
* There are some Windows CLI utilities that have the same name as some bash utilities (whcih is why that big red warning exists in the first place) so there are quite legitimate reasons for your scripting environment to not by default have these utilities available -- since it can break CMD scripts.

At the end of the day these issues are significant, and while perhaps it's possible to write something using shell scripting that can work most of the time for most people, it will never work for everyone in configurations that are entirely common.

So rather than fighting against all these configuration differences, it seems a lot easier to just not use the shell unless you have no other choice. Code like this:

    '  [ -f package.json ] && cat package.json | grep -q "\\"$1\\"\\s*:"',

can be pretty easily written entirely in node and be 100% compatible with any windows, linux or mac user. If the goal is to create software that "just works" for everyone then the best way is to not depend on the user's environment. Obviously we still have to use git itself, but ideally this would be the only thing you run from outside node. 

I don't know too much about the mac GUI issue and `nvm` that has been referenced here, but already in the code I can see that's only applicable to non-windows users. So if that is something that works well for those environments then no reason just not to have it be a different code path for them.

**Comment by jamietre** [comment]
Well.. I didn't mean to just drop the mic after that post... was really just trying to be as comprehensive as possible about why it's so difficult to use scripting and be compatible with windows! :)

@typicode we have a pretty big investment in standardized commit hooks since we use git with large teams of varying abilities, and I'd be very happy to be contribute to the solution as long as it's agreeable. I'd definitely prefer to use something that's not officially deprecated and has broader community support. I can write the code to do this with node instead of shell scripts if you're OK with the architectural change.

**Comment by typicode** [comment]
> Well.. I didn't mean to just drop the mic after that post... 

No worries :) just wanted to take time to better understand this case. So thanks for the details.

Actually, even in CMD, shell scripts started with Git will work:

```sh
C:\Users\typicode\git-test>ls # will of course fail
# .git/hooks/pre-commit
# #!/bin/sh
# ls
C:\Users\typicode\git-test>git commit -am test # will correctly output ls
```

And so this works in IDE too, as Git will run hook scripts and they won't be run directly in CMD. I've tested it with Visual Studio Code which comes with Git built-in.

Also AFAICT from Windows related issues, hook scripts are always run. When they failed on Windows it was because of small differences like path that needed to be normalized.

I would suggest trying husky with some of your work configuration. It's easy to remove if it doesn't work for you or some of your team.

```sh
npm install husky # add --save-dev if you want to make it available to your team
npm remove husky # will remove hooks that husky installed
```

Existing hooks won't be touched.

> mac GUI issue and nvm

This affects people that have installed Node using only `nvm` on OS X or Linux.

With `nvm`, PATH is only modified in the terminal, so when you start a GUI app it will get a different PATH and won't be able to find Node.

In this configuration, if hook scripts are written using Node it won't work. With a shell script it's easy to load `nvm` and `node`.

Also I think running a shell script is slightly faster than loading Node.

> node instead of shell script

On OS X and Linux, I prefer to keep shell for the previous reason.

On Windows not against it and it may be a good idea, but I would like to have at least a failing scenario on this platform (install tool X, run command Y, ...) before creating a specific hook script.

Hope it clarifies things and that I didn't miss the point.

**Comment by jamietre** [comment]
This is interesting. So it seems possible my central concern may be, er, "alternate facts" because what I didn't consider is that the scripts are always launched by git, rather than from a separate node process which will spawn a new default command processor via the OS. I might still argue that parsing `package.json` is trivial enough to do with node that it still is sensible, generally speaking, but if we're already in a bash script then maybe it's pointless.

I still have a bit of a nagging feeling but maybe it's not a big deal (at least not for us). There are certainly scenarios that could potentially be incompatible. For example, if you are using a git client other than Git for Windows, e.g. [git package for msys2](https://github.com/Alexpux/MSYS2-packages/tree/master/git). But frankly this is edge-casey enough that it's probably not worth a major philosophy change to support.

I'll give husky a try in a few different configs to be sure I'm not overlooking anything else here. But assuming I can't blow it up at a fundamental level, if the open windows issue is simply a path parsing problem then consider my concerns allayed.

**Comment by typicode** [comment]
> git package for msys2

If it can help, it seems it works too https://github.com/typicode/husky/pull/70 but I've not tried it myself.

**Comment by jamietre** [comment]
The scenario I can imagine is that you're running git in an environment where it can't find the shell. I don't know how git integrates with the shell when it invokes it (but obviously it's not through windows -- or it wouldn't work anywhere), but I was able to make it fail when using msys2 with a cmd shell like this:

install MSYS2
install git: `pacman -S git`
launch a CMD shell
remove git for windows from your path (if it's also installed)

Commit hooks are ignored. Strangely it seems to work fine with TCC/LE? I don't really know why this would behave differently in TCC vs CMD

I am really not worried about this. I actually am almost that edge case... I use MSYS2 for bash commands on windows, and TCC/LE for my shell (whcih is not bash but CMD replacement). I do this because I like the package manager and the availability of all the tools that don't come with Git for Windows, and TCC/LE is far better than bash for usability. But at the end of the day I have a hard time imagining someone being enough of a hacker that they want to use MSYS2, and using MSYS2 git, and using it on CMD instead of a shell replacement.

I am satisfied that the fundamental problem I feared (scripts not working because default windows command shell isn't bash) doesn't exist... and I suspect that anyone who was trying to work in the contrived scenario I created would have other problems anyway.

**Comment by uglow** [comment]
I've tried upgrading a ghook commit-msg hook to husky, and I'm finding that the commit message isn't passed to the Node script as it was when using ghooks.

This works using ghooks:
``` json
"config": {
    "commitizen": {
      "path": "node_modules/cz-customizable"
    },
    "cz-customizable": {
      "config": "config/release/commitMessageConfig.js"
    },
    "ghooks": {
      "commit-msg": "node ./node_modules/cz-customizable-ghooks/lib/index.js $2",
    }
  },
```

Note the `$2` parameter which is the path to the file containing the commit message.

When using husky, no additional arguments seem to be being passed to the script, so it fails. So at the moment, husky is NOT a like-for-like replacement (or enhanced version) of ghooks.

CC @typicode.

**Comment by typicode** [comment]
hi @uglow,

You should be able to find additional arguments in `GIT_PARAMS` environment variable.

**Comment by duclet** [comment]
Hmm, just stumbled upon this news today. I have used husky in the past and went with ghooks because I felt it was better designed. The biggest flaw for me with husky is that it put the scripts inside of the `scripts` block. That makes it conflicts with how NPM automatically runs `pre` and `post` versions of that command as well. That being such an integral part of how husky works though, I doubt it can be fixed. I wouldn't mind taking over this project.

**Comment by gtramontina** [comment]
@duclet I'd be more than happy to move this repo into an organization and add you as contributor. Let me know!

**Comment by kentcdodds** [comment]
I imagine that @typicode may entertain the idea of allowing config in a similar way that ghooks had if it means there's more effort behind husky rather than split-effort between two tools. Has anyone asked?

**Comment by duclet** [comment]
@gtramontina, that would be great.

@kentcdodds, there are two open tickets relating to this matter that doesn't seem like it is going anywhere anytime soon.

**Comment by jamietre** [comment]
I think there is room in the world for more than one project with similar goals. Competition is the catalyst of innovation right?

@duclet In addition to your design concerns, even if possible to do with the shell, I still think that it's just common sense to use Node to do file system stuff. I'm glad you are keeping this alive. Officially canceling plans to migrate.

**Comment by typicode** [comment]
Hi,

Just replied here https://github.com/typicode/husky/issues/99
feedback about usage and conflicts is welcome

**Comment by duclet** [comment]
I still have concerns but I did make a recommendation in that ticket which I can live with. We'll see how it goes but if not, I would still like to take over this project if possible. Thanks.

**Comment by jhabdas** [comment]
> I would still like to take over this project if possible.

I would like to see that happen. I feel it's a shame to fold into a single repo when competition breeds innovation and allows libraries to grow to meet specific user demands, giving choice.

**Comment by jhabdas** [comment]
@duclet fyi https://github.com/typicode/husky/issues/133

**Comment by jhabdas** [comment]
@duclet I waited 20 days for a husky maintainer to address my concerns and it was a ghost town. I've decided to return to using `ghooks` library and left final justification here: https://github.com/typicode/husky/issues/133#issuecomment-309291314

@gtramontina Please offer to transfer ownership of this repo. I _really_ don't need a script called `precommit` to run my script called `lint`. That's like mixing oil and water. I also don't appreciate the way this deprecation took place given hoards of users are now doing what I refuse to do. TBH I'd rather super glue a post-it note to my monitor reminding me to run my linter than pollute my `scripts` section with the opinion of a dev dependency.

**Comment by jhabdas** [comment]
@duclet please lmk if you'd like an invite to the ghooks-org @gtramontina set up so we can revive this puppy.

**Comment by gtramontina** [comment]
Alright…

I've just moved `ghooks` to its own org [`ghooks-org`](https://github.com/ghooks-org) – [`ghooks`](github.com/ghooks) was already taken – and invited those who expressed interest in keeping `ghooks` alive to be part of it. cc/ @jhabdas @duclet @ta2edchimp

I still have to figure out npm ownership transfer. Tips and hints are welcome!

Hope this helps the community! 🍻

_(had this message sitting here when my battery died)_

**Comment by gtramontina** [comment]
By the way, I got the logo from https://www.viget.com/articles/two-ways-to-share-git-hooks-with-your-team -- we should probably add an attribution somewhere (or come up with a new one – anyone with design skills? 😄)

**Comment by jhabdas** [comment]
@gtramontina It's not super usual for most git projects to do this yet, but it might be fun to set up a donation request form to a shared bitcoin account and hope to score some coin for your efforts.
